version: '3.8'

services:
  bot:
    build: .
    image: ghcr.io/tkaixiang/storeman-bot:latest
    restart: unless-stopped
    networks:
      - storeman-bot-v2_default
    secrets:
      - source: dotenv
        target: /app/.env
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    networks:
      - storeman-bot-v2_default
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

secrets:
  dotenv: 
    file: ./.env

networks:
  storeman-bot-v2_default:
    external: true
